CREATE TABLE DOCTOR_INFO
(
    DOC_UNAME VARCHAR(25) NOT NULL,
    DOC_PWD VARCHAR(15) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    SALARY DECIMAL(7,2),
    SPECIALTY VARCHAR(25),
    PHONE# VARCHAR(12),
    AVAILABLE_DATE DATE,
    AVAILABLE_TIME VARCHAR(20),
    FK_DOC_UNAME VARCHAR(25),
    PRIMARY KEY(DOC_UNAME),
    FOREIGN KEY(FK_DOC_UNAME) REFERENCES DOCTOR_INFO(DOC_UNAME) ON DELETE CASCADE
);

CREATE TABLE NURSE_INFO
(
    NRS_UNAME VARCHAR(30) NOT NULL,
    NRS_PWD VARCHAR(15) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    SALARY DECIMAL(7,2),
    SPECIALTY VARCHAR(25),
    NRS_FK_DOC_UNAME VARCHAR(20),
    PRIMARY KEY(NRS_UNAME),
    FOREIGN KEY(NRS_FK_DOC_UNAME) REFERENCES DOCTOR_INFO(DOC_UNAME) ON DELETE CASCADE
);

CREATE TABLE RECEPTIONIST_INFO
(
    REC_UNAME VARCHAR(25) NOT NULL,
    REC_PWD VARCHAR(15) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    SALARY DECIMAL(7,2),
    PRIMARY KEY(REC_UNAME)
);

CREATE TABLE ACCOUNTANT_INFO
(
    ACC_UNAME VARCHAR(25) NOT NULL,
    ACC_PWD VARCHAR(15) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    SALARY DECIMAL(7,2),
    PRIMARY KEY(ACC_UNAME)
);

CREATE TABLE PATIENT_INFO
(
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    GENDER VARCHAR(12) NOT NULL,
    PT_PHONE# VARCHAR(12),
    STREET VARCHAR(30),
    CITY VARCHAR(30),
    STATE VARCHAR(20),
    ZIP_CODE VARCHAR(5),
    SSN CHAR(9) NOT NULL,
    PID INTEGER NOT NULL,
    TREATMENT_NAME VARCHAR(30),
    TREATMENT_COST FLOAT,
    PRESCRIPTION VARCHAR(25),
    ADMISSION_DATE DATE,
    ADMISSION_TIME VARCHAR(20),
    DISCHARGE_DATE DATE,
    DISCHARGE_TIME VARCHAR(20),
    P_FK_DOC_UNAME VARCHAR(25),
    P_FK_NRS_UNAME VARCHAR(25),
    P_FK_REC_UNAME VARCHAR(25),
    P_FK_ACC_UNAME VARCHAR(25),
    PRIMARY KEY(SSN,PID),
    FOREIGN KEY(P_FK_DOC_UNAME) REFERENCES DOCTOR_INFO(DOC_UNAME) ON DELETE CASCADE,
    FOREIGN KEY(P_FK_NRS_UNAME) REFERENCES NURSE_INFO(NRS_UNAME) ON DELETE CASCADE,
    FOREIGN KEY(P_FK_REC_UNAME) REFERENCES RECEPTIONIST_INFO(REC_UNAME) ON DELETE CASCADE,
    FOREIGN KEY(P_FK_ACC_UNAME) REFERENCES ACCOUNTANT_INFO(ACC_UNAME) ON DELETE CASCADE
);

CREATE TABLE PATIENT_INSURANCE_DETAILS
(
    INSURANCE_NAME VARCHAR(30),
    INSURANCE_COMPANY_NAME VARCHAR(35),
    INSURANCE_TYPE VARCHAR(25),
    INSURANCE_ID VARCHAR(10),
    PI_FK_SSN CHAR(9) NOT NULL,
    PI_FK_PID INTEGER NOT NULL,
    PRIMARY KEY(INSURANCE_ID),
    FOREIGN KEY(PI_FK_SSN,PI_FK_PID) REFERENCES PATIENT_INFO(SSN,PID) ON DELETE CASCADE
);

CREATE TABLE MEDICINE_DETAILS
(
    MED_NAME VARCHAR(25) NOT NULL,
    MED_COST FLOAT,
    MED_DOSE VARCHAR(15),
    MED_FK_SSN CHAR(9) NOT NULL,
    MED_FK_PID INTEGER NOT NULL,
    PRIMARY KEY(MED_NAME),
    FOREIGN KEY(MED_FK_SSN,MED_FK_PID) REFERENCES PATIENT_INFO(SSN,PID) ON DELETE CASCADE
);

CREATE TABLE DIAGNOSIS_DETAILS
(
    CPT_CODE VARCHAR(5) NOT NULL,
    PROCEDURE_NAME VARCHAR(30),
    DIAGNOSIS_COST FLOAT,
    DIGNOSIS_NAME VARCHAR(35),
    DIG_FK_SSN CHAR(9),
    DIG_FK_PID INTEGER,
    PRIMARY KEY(CPT_CODE),
    FOREIGN KEY(DIG_FK_SSN,DIG_FK_PID) REFERENCES PATIENT_INFO(SSN,PID) ON DELETE CASCADE
);

CREATE TABLE REGISTRATION_DETAILS
(
    CHIEF_COMPLAINT VARCHAR(40) NOT NULL,
    DEPARTMENT VARCHAR(20),
    ROOM_NUMBER INTEGER,
    TRANSPORT_MODE VARCHAR(25),
    REG_FK_SSN CHAR(9),
    REG_FK_PID INTEGER NOT NULL,
    PRIMARY KEY(CHIEF_COMPLAINT,DEPARTMENT),
    FOREIGN KEY(REG_FK_SSN,REG_FK_PID) REFERENCES PATIENT_INFO(SSN,PID) ON DELETE CASCADE
);
 
CREATE TABLE TREATMENT_DETAILS
(
    TREATMENT_DATE DATE,
    TD_FK_DOC_UNAME VARCHAR(25),
    TD_FK_SSN CHAR(9),
    TD_FK_PID INTEGER NOT NULL,
    PRIMARY KEY(TD_FK_DOC_UNAME,TD_FK_PID,TD_FK_SSN,TREATMENT_DATE),
    FOREIGN KEY(TD_FK_SSN,TD_FK_PID) REFERENCES PATIENT_INFO(SSN,PID) ON DELETE CASCADE,
    FOREIGN KEY(TD_FK_DOC_UNAME) REFERENCES DOCTOR_INFO(DOC_UNAME) ON DELETE CASCADE
);
